//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xecrets.File.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xecrets.File.Cli.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gpl_3_0 {
            get {
                return ResourceManager.GetString("gpl_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** IMPORTANT ***
        ///
        ///Always test on copies of non-essential files before using this program on real data. Encryption is
        ///no protection against data loss, always keep adequate backups of your important files.
        ///
        ///There is no backdoor or password reset function! If you encrypt a file, and do not know the original
        ///password or have access to a private key matching a public key used when encrypting the file, the
        ///contents of the file is irretrievably lost and cannot be recovered.
        ///
        ///Xecrets File Cli is distribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_details {
            get {
                return ResourceManager.GetString("help_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] index {
            get {
                object obj = ResourceManager.GetObject("index", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subscription for {licensee} valid to {expiration}, thank you!\nVisit https://www.axantum.com/ for updates..
        /// </summary>
        internal static string LicensedDownloadBlurb {
            get {
                return ResourceManager.GetString("LicensedDownloadBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subscription for {licensee} expired at {expiration}.\nUse an older build, or buy a new subscription at https://www.axantum.com/ ..
        /// </summary>
        internal static string LicensedExpiredDownloadBlurb {
            get {
                return ResourceManager.GetString("LicensedExpiredDownloadBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download subscription &apos;{product}&apos; for {licensee} is not valid for this download.\nVisit https://www.axantum.com/ for information..
        /// </summary>
        internal static string LicenseNotValidForProductBlurb {
            get {
                return ResourceManager.GetString("LicenseNotValidForProductBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE57HBftSv6/K0Fxm+IQRAqY7E3/dr
        ///+6kW/2c687JxT3MgChMZ+mimqrlRklmMghcNMG6lMx806YNbusGmpHrq4g==
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string LicensePublicKeyProduction {
            get {
                return ResourceManager.GetString("LicensePublicKeyProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbehILxdHBD1NG6EYAIDzEbdumyL0
        ///Idyr4Ko9NUmkM4V6HGk0HUD0lmIM0l1WTppDFoKfdOflwpxXqISTTjQODg==
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string LicensePublicKeyTest {
            get {
                return ResourceManager.GetString("LicensePublicKeyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xecrets File Command Line - A cross platform AxCrypt compatible tool for applied strong cryptography.
        ///Portions Copyright 2023, Svante Seleborg, All Rights Reserved.
        ///BETA {gpl} Version {version} {buildutc} {runtime}
        ///
        ///This program is free software; It is licensed under GNU General Public License version 3 or any later version.
        ///
        ///{blurb}.
        /// </summary>
        internal static string splash {
            get {
                return ResourceManager.GetString("splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please support development, buy a download subscription at https://www.axantum.com/ ..
        /// </summary>
        internal static string UnlicensedOrGplBlurb {
            get {
                return ResourceManager.GetString("UnlicensedOrGplBlurb", resourceCulture);
            }
        }
    }
}
